key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint: 'https://acme-v01.api.letsencrypt.org/'
domains: []
public: []
output_dir: '~/le_certs/'
letsencrypt_account_email: ''
api_url: 'https://api.webfaction.com/'
username: ''
password: ''
servername: ''
cert_name: ''
quiet: false
